/**
 * Deploy LocalMockDrop to a running local Hardhat node and pre-fund the
 * developer wallet with test ETH.
 *
 * Usage:
 *   # terminal 1
 *   npm run chain:local
 *
 *   # terminal 2
 *   npm run contract:deploy:local
 *
 * Writes .env.localchain.generated with the deployed address + chain config.
 * Copy those values into .env.local to point the Next.js site at the local
 * chain.
 *
 * Local private keys: the Hardhat node ships 20 deterministic accounts
 * (private keys hard-coded in Hardhat). They are FAKE, public, and used
 * worldwide for tests. Do not send real funds to them, ever.
 */
import fs from "node:fs";
import path from "node:path";
// Hardhat 2.x ships as CommonJS. Node 22+ resolves this script as ESM, so we
// use the default import + destructure pattern Hardhat recommends.
import hre from "hardhat";
const { ethers, network } = hre;

// KB's wallet on file. Pre-funded with test ETH so KB can mint from his
// real MetaMask address without importing any private keys.
const KB_WALLET = "0x6D0ab0B66EF699FDb5f8e8af69FcFcb395D4208E";

// Where token JSON metadata lives (testnet style, served by Vercel). Each
// tokenURI(id) resolves to "<BASE_URI><id>.json", e.g.
// https://.../metadata/0.json (note: this mock starts ids at 0).
const BASE_URI = "https://braintrust-collection.vercel.app/metadata/";

const NAME = "Braintrust Collection (Local)";
const SYMBOL = "BTC-L";
const MAX_SUPPLY = 15;

async function main() {
  if (network.name !== "localhost" && network.name !== "hardhat") {
    throw new Error(
      `This script is only for local chains. Got network "${network.name}".`
    );
  }

  const [deployer] = await ethers.getSigners();
  console.log("=== LocalMockDrop deploy ===");
  console.log(`  Network:  ${network.name} (chainId ${(await ethers.provider.getNetwork()).chainId})`);
  console.log(`  Deployer: ${deployer.address}`);
  console.log(`  Balance:  ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH`);

  // Deploy
  const Factory = await ethers.getContractFactory("LocalMockDrop");
  const contract = await Factory.deploy(NAME, SYMBOL, MAX_SUPPLY);
  await contract.waitForDeployment();
  const address = await contract.getAddress();
  console.log(`  Contract: ${address}`);

  // Set base URI
  const tx = await contract.setBaseURI(BASE_URI);
  await tx.wait();
  console.log(`  baseURI:  ${BASE_URI}`);

  // Pre-fund KB's wallet with 10 test ETH so he can mint without importing
  // any private keys. Just connect MetaMask to the localhost network and the
  // funds will appear.
  const fundTx = await deployer.sendTransaction({
    to: KB_WALLET,
    value: ethers.parseEther("10"),
  });
  await fundTx.wait();
  console.log(`  Funded:   ${KB_WALLET} with 10 ETH (local only)`);

  // Sanity check: read back claim condition
  const condition = await contract.getClaimConditionById(0);
  console.log(
    `  Phase:    price=${condition.pricePerToken}, perWallet=${condition.quantityLimitPerWallet}, supply=${condition.maxClaimableSupply}`
  );

  // Write env file for Next.js
  const envOut = path.join(process.cwd(), ".env.localchain.generated");
  const envContent =
    `# AUTO-GENERATED by scripts/deploy-local-contract.ts
# Local Hardhat blockchain only. DO NOT use these values for any real chain.
# Re-run \`npm run contract:deploy:local\` if you restart the node.

NEXT_PUBLIC_CHAIN_ID=31337
NEXT_PUBLIC_CHAIN_NAME=Localhost
NEXT_PUBLIC_RPC_URL=http://127.0.0.1:8545
NEXT_PUBLIC_CONTRACT_ADDRESS=${address}
NEXT_PUBLIC_CONTRACT_MODE=local-mock-drop
NEXT_PUBLIC_TOTAL_SUPPLY=15
NEXT_PUBLIC_MINT_PRICE=0
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=1244257340c4eca87602fb431b8ec3a9
NEXT_PUBLIC_BASE_IMAGE_URI=${BASE_URI}
` ;
  fs.writeFileSync(envOut, envContent);
  console.log(`  Wrote:    ${envOut}`);

  // Print Hardhat test accounts so KB can see them if he wants.
  const accounts = await ethers.getSigners();
  console.log("\n  Hardhat test accounts (FAKE, dev only):");
  for (let i = 0; i < Math.min(5, accounts.length); i++) {
    const a = accounts[i];
    const bal = await ethers.provider.getBalance(a.address);
    console.log(`    ${i}: ${a.address}  ${ethers.formatEther(bal)} ETH`);
  }

  console.log("\nNext steps:");
  console.log("  1. cp .env.localchain.generated .env.local");
  console.log("  2. npm run dev  (Next.js dev server on http://localhost:3000)");
  console.log("  3. In MetaMask, add Localhost network: RPC http://127.0.0.1:8545, chainId 31337");
  console.log("  4. Click Connect Wallet on the site, pick Localhost, mint.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
